# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/x_fft0/x_fft0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x_fft0 || ORIG_REF_NAME==x_fft0} -quiet] -quiet

# IP: bd/x_fft0/ip/x_fft0_xfft_0_0/x_fft0_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==x_fft0_xfft_0_0 || ORIG_REF_NAME==x_fft0_xfft_0_0} -quiet] -quiet

# XDC: c:/Users/gm/Vivado Projects/primer_test/primer_test.gen/sources_1/bd/x_fft0/x_fft0_ooc.xdc
